# Generated by Django 5.0.2 on 2024-03-01 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='msgs',
            table='msg_translation',
        ),
    ]
