# Generated by Django 5.0.2 on 2024-03-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_msgs_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceStatuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'resource_statuses',
                'managed': False,
            },
        ),
    ]
