# Generated by Django 5.0.2 on 2024-03-10 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resourcestatuses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'managed': False, 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='langs',
            options={'managed': False, 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='msgs',
            options={'managed': False, 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='resources',
            options={'managed': False, 'verbose_name_plural': 'Resources'},
        ),
        migrations.AlterModelOptions(
            name='resourcestatuses',
            options={'managed': False, 'verbose_name_plural': 'Resource Statuses'},
        ),
        migrations.AlterModelOptions(
            name='resourcetypes',
            options={'managed': False, 'verbose_name_plural': 'Resource Types'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'managed': False, 'verbose_name_plural': 'Tags'},
        ),
    ]
